In [11]:
from astropy.table import Table
import pandas as pd

gal_info = "../data/SFR/gal_info_dr7_v5_2.fit"
ignore_cols = ['PHOTOID', 'PLUG_MAG', 'SPECTRO_MAG', 'KCOR_MAG', 'KCOR_MODEL_MAG']


data_info = Table.read(gal_info, format='fits')
for col in ignore_cols:
    del data_info[col]
data_info.convert_bytestring_to_unicode()
df1 = data_info.to_pandas()
df1

     TARGETTYPE
-------------------
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
                ...
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
GALAXY
Length = 927552 rows

,PLATEID,MJD,FIBERID,RA,DEC,PRIMTARGET,SECTARGET,TARGETTYPE,SPECTROTYPE,SUBCLASS,Z,Z_ERR,Z_WARNING,V_DISP,V_DISP_ERR,SN_MEDIAN,E_BV_SFD,ZTWEAK,ZTWEAK_ERR,RELEASE
0,266,51602,1,146.714203,-1.041304,96,0,GALAXY,GALAXY,,0.021275,0.000009,0,135.899567,4.085766,38.082611,0.055224,0.0,0.0,extra
1,266,51602,2,146.919449,-0.990492,64,0,GALAXY,GALAXY,,0.213925,0.000052,0,140.481186,15.037567,6.479208,0.059835,0.0,0.0,extra
2,266,51602,4,146.859833,-0.808902,96,0,GALAXY,GALAXY,,0.126554,0.000062,0,201.574417,18.037975,9.122138,0.056508,0.0,0.0,extra
3,266,51602,5,146.763397,-0.810433,32,0,GALAXY,GALAXY,,0.448645,0.000168,0,240.905869,69.598114,2.452963,0.060821,0.0,0.0,extra
4,266,51602,6,146.963898,-0.545003,64,0,GALAXY,GALAXY,STARBURST,0.055988,0.000011,0,47.055084,38.030617,5.252150,0.114275,0.0,0.0,extra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927547,2974,54592,633,260.743164,31.944035,64,0,GALAXY,GALAXY,,0.033870,0.000009,0,102.931534,3.445269,34.720165,0.037327,0.0,0.0,dr7.2
927548,2974,54592,635,260.800568,31.898993,64,0,GALAXY,GALAXY,STARFORMING BROADLINE,0.159622,0.000023,0,210.749359,9.568452,18.576582,0.035961,0.0,0.0,dr7.2
927549,2974,54592,636,260.716003,32.024277,96,0,GALAXY,GALAXY,,0.167358,0.000030,0,230.786392,10.088615,17.448772,0.038862,0.0,0.0,dr7.2
927550,2974,54592,637,260.697235,32.285629,64,0,GALAXY,GALAXY,,0.111548,0.000017,0,196.624634,6.668476,24.761684,0.041596,0.0,0.0,dr7.2
927551,2974,54592,638,260.716248,32.092903,96,0,GALAXY,GALAXY,,0.223957,0.000034,0,280.104553,11.593746,14.562586,0.040419,0.0,0.0,dr7.2

In [12]:
gal_fibsfr = "../data/SFR/gal_fibsfr_dr7_v5_2.fits"

from astropy.table import Table
data_fibsfr = Table.read(gal_fibsfr, format='fits')
df2 = data_fibsfr.to_pandas()
df2

,AVG,ENTROPY,MEDIAN,MODE,P16,P2P5,P84,P97P5
0,-1.543461,-6.338328,-1.320937,-0.90,-2.706613,-4.130714,-0.593553,0.022953
1,-0.919403,-6.355593,-0.688796,-0.30,-2.083375,-3.577018,0.034467,0.666007
2,-1.441842,-6.365195,-1.315850,-0.80,-2.601916,-3.709935,-0.435525,0.192519
3,-1.000000,0.000000,-1.000000,-1.00,-1.000000,-1.000000,-1.000000,-1.000000
4,-0.829663,-4.432269,-0.890750,-0.90,-1.117369,-1.299526,-0.593434,-0.208450
...,...,...,...,...,...,...,...,...
927547,-2.213865,-4.733822,-2.235181,-2.25,-2.503285,-2.987607,-1.938026,-1.557104
927548,-1.210697,-6.379048,-1.003444,-0.55,-2.406285,-3.758203,-0.221807,0.390518
927549,-0.941041,-6.386897,-0.772978,-0.25,-2.135459,-3.363456,0.069779,0.684122
927550,-1.584332,-6.370047,-1.448591,-0.90,-2.753753,-3.889770,-0.575740,0.044787
927551,-1.138256,-6.379399,-0.978988,-0.45,-2.325594,-3.525856,-0.128533,0.480836

In [14]:
df_concat = pd.concat([df1, df2], axis=1)
df_concat

,PLATEID,MJD,FIBERID,RA,DEC,PRIMTARGET,SECTARGET,TARGETTYPE,SPECTROTYPE,SUBCLASS,...,ZTWEAK_ERR,RELEASE,AVG,ENTROPY,MEDIAN,MODE,P16,P2P5,P84,P97P5
0,266,51602,1,146.714203,-1.041304,96,0,GALAXY,GALAXY,,...,0.0,extra,-1.543461,-6.338328,-1.320937,-0.90,-2.706613,-4.130714,-0.593553,0.022953
1,266,51602,2,146.919449,-0.990492,64,0,GALAXY,GALAXY,,...,0.0,extra,-0.919403,-6.355593,-0.688796,-0.30,-2.083375,-3.577018,0.034467,0.666007
2,266,51602,4,146.859833,-0.808902,96,0,GALAXY,GALAXY,,...,0.0,extra,-1.441842,-6.365195,-1.315850,-0.80,-2.601916,-3.709935,-0.435525,0.192519
3,266,51602,5,146.763397,-0.810433,32,0,GALAXY,GALAXY,,...,0.0,extra,-1.000000,0.000000,-1.000000,-1.00,-1.000000,-1.000000,-1.000000,-1.000000
4,266,51602,6,146.963898,-0.545003,64,0,GALAXY,GALAXY,STARBURST,...,0.0,extra,-0.829663,-4.432269,-0.890750,-0.90,-1.117369,-1.299526,-0.593434,-0.208450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927547,2974,54592,633,260.743164,31.944035,64,0,GALAXY,GALAXY,,...,0.0,dr7.2,-2.213865,-4.733822,-2.235181,-2.25,-2.503285,-2.987607,-1.938026,-1.557104
927548,2974,54592,635,260.800568,31.898993,64,0,GALAXY,GALAXY,STARFORMING BROADLINE,...,0.0,dr7.2,-1.210697,-6.379048,-1.003444,-0.55,-2.406285,-3.758203,-0.221807,0.390518
927549,2974,54592,636,260.716003,32.024277,96,0,GALAXY,GALAXY,,...,0.0,dr7.2,-0.941041,-6.386897,-0.772978,-0.25,-2.135459,-3.363456,0.069779,0.684122
927550,2974,54592,637,260.697235,32.285629,64,0,GALAXY,GALAXY,,...,0.0,dr7.2,-1.584332,-6.370047,-1.448591,-0.90,-2.753753,-3.889770,-0.575740,0.044787
927551,2974,54592,638,260.716248,32.092903,96,0,GALAXY,GALAXY,,...,0.0,dr7.2,-1.138256,-6.379399,-0.978988,-0.45,-2.325594,-3.525856,-0.128533,0.480836

In [17]:
h5_path = "../results/SDSS_cube_big.h5"
import pandas as pd

h5_file = pd.HDFStore(h5_path)
h5_file.put("star_formation_rates", df_concat, format="table")

In [18]:
h5_file["star_formation_rates"]

,PLATEID,MJD,FIBERID,RA,DEC,PRIMTARGET,SECTARGET,TARGETTYPE,SPECTROTYPE,SUBCLASS,...,ZTWEAK_ERR,RELEASE,AVG,ENTROPY,MEDIAN,MODE,P16,P2P5,P84,P97P5
0,266,51602,1,146.714203,-1.041304,96,0,GALAXY,GALAXY,,...,0.0,extra,-1.543461,-6.338328,-1.320937,-0.90,-2.706613,-4.130714,-0.593553,0.022953
1,266,51602,2,146.919449,-0.990492,64,0,GALAXY,GALAXY,,...,0.0,extra,-0.919403,-6.355593,-0.688796,-0.30,-2.083375,-3.577018,0.034467,0.666007
2,266,51602,4,146.859833,-0.808902,96,0,GALAXY,GALAXY,,...,0.0,extra,-1.441842,-6.365195,-1.315850,-0.80,-2.601916,-3.709935,-0.435525,0.192519
3,266,51602,5,146.763397,-0.810433,32,0,GALAXY,GALAXY,,...,0.0,extra,-1.000000,0.000000,-1.000000,-1.00,-1.000000,-1.000000,-1.000000,-1.000000
4,266,51602,6,146.963898,-0.545003,64,0,GALAXY,GALAXY,STARBURST,...,0.0,extra,-0.829663,-4.432269,-0.890750,-0.90,-1.117369,-1.299526,-0.593434,-0.208450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927547,2974,54592,633,260.743164,31.944035,64,0,GALAXY,GALAXY,,...,0.0,dr7.2,-2.213865,-4.733822,-2.235181,-2.25,-2.503285,-2.987607,-1.938026,-1.557104
927548,2974,54592,635,260.800568,31.898993,64,0,GALAXY,GALAXY,STARFORMING BROADLINE,...,0.0,dr7.2,-1.210697,-6.379048,-1.003444,-0.55,-2.406285,-3.758203,-0.221807,0.390518
927549,2974,54592,636,260.716003,32.024277,96,0,GALAXY,GALAXY,,...,0.0,dr7.2,-0.941041,-6.386897,-0.772978,-0.25,-2.135459,-3.363456,0.069779,0.684122
927550,2974,54592,637,260.697235,32.285629,64,0,GALAXY,GALAXY,,...,0.0,dr7.2,-1.584332,-6.370047,-1.448591,-0.90,-2.753753,-3.889770,-0.575740,0.044787
927551,2974,54592,638,260.716248,32.092903,96,0,GALAXY,GALAXY,,...,0.0,dr7.2,-1.138256,-6.379399,-0.978988,-0.45,-2.325594,-3.525856,-0.128533,0.480836

In [41]:
import ujson

spectra_metadata = h5_file["fits_spectra_metadata"]["header"]
extracted = [ujson.decode(header) for header in spectra_metadata]
spectra_headers = pd.DataFrame.from_dict(extracted)
spectra_headers

,SIMPLE,BITPIX,NAXIS,EXTEND,TAI,RA,DEC,EQUINOX,RADECSYS,TAIHMS,...,EXPID03,EXPID04,EXPID05,EXPID06,EXPID07,EXPID08,EXPID09,EXPID10,EXPID11,EXPID12
0,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,b2-00008084-00008085-00008086,b2-00008149-00008153-00008154,b2-00008150-00008153-00008154,b2-00008151-00008153-00008154,r2-00008082-00008085-00008086,r2-00008083-00008085-00008086,r2-00008084-00008085-00008086,r2-00008149-00008153-00008154,r2-00008150-00008153-00008154,r2-00008151-00008153-00008154
1,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,b1-00008084-00008085-00008086,b1-00008149-00008153-00008154,b1-00008150-00008153-00008154,b1-00008151-00008153-00008154,r1-00008082-00008085-00008086,r1-00008083-00008085-00008086,r1-00008084-00008085-00008086,r1-00008149-00008153-00008154,r1-00008150-00008153-00008154,r1-00008151-00008153-00008154
2,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,b2-00008084-00008085-00008086,b2-00008149-00008153-00008154,b2-00008150-00008153-00008154,b2-00008151-00008153-00008154,r2-00008082-00008085-00008086,r2-00008083-00008085-00008086,r2-00008084-00008085-00008086,r2-00008149-00008153-00008154,r2-00008150-00008153-00008154,r2-00008151-00008153-00008154
3,True,8,0,True,4.477028e+09,45.787818,-0.017770,2000.0,FK5,10:36:49.28,...,b1-00006800-00006802-00006803,r1-00006798-00006802-00006803,r1-00006799-00006802-00006803,r1-00006800-00006802-00006803,NaN,NaN,NaN,NaN,NaN,NaN
4,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,b1-00008084-00008085-00008086,b1-00008149-00008153-00008154,b1-00008150-00008153-00008154,b1-00008151-00008153-00008154,r1-00008082-00008085-00008086,r1-00008083-00008085-00008086,r1-00008084-00008085-00008086,r1-00008149-00008153-00008154,r1-00008150-00008153-00008154,r1-00008151-00008153-00008154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,b1-00008084-00008085-00008086,b1-00008149-00008153-00008154,b1-00008150-00008153-00008154,b1-00008151-00008153-00008154,r1-00008082-00008085-00008086,r1-00008083-00008085-00008086,r1-00008084-00008085-00008086,r1-00008149-00008153-00008154,r1-00008150-00008153-00008154,r1-00008151-00008153-00008154
1916,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,b2-00008084-00008085-00008086,b2-00008149-00008153-00008154,b2-00008150-00008153-00008154,b2-00008151-00008153-00008154,r2-00008082-00008085-00008086,r2-00008083-00008085-00008086,r2-00008084-00008085-00008086,r2-00008149-00008153-00008154,r2-00008150-00008153-00008154,r2-00008151-00008153-00008154
1917,True,8,0,True,4.477028e+09,45.787818,-0.017770,2000.0,FK5,10:36:49.28,...,b2-00006800-00006802-00006803,r2-00006798-00006802-00006803,r2-00006799-00006802-00006803,r2-00006800-00006802-00006803,NaN,NaN,NaN,NaN,NaN,NaN
1918,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,b1-00008084-00008085-00008086,b1-00008149-00008153-00008154,b1-00008150-00008153-00008154,b1-00008151-00008153-00008154,r1-00008082-00008085-00008086,r1-00008083-00008085-00008086,r1-00008084-00008085-00008086,r1-00008149-00008153-00008154,r1-00008150-00008153-00008154,r1-00008151-00008153-00008154
1919,True,8,0,True,4.477028e+09,45.787818,-0.017770,2000.0,FK5,10:36:49.28,...,b2-00006800-00006802-00006803,r2-00006798-00006802-00006803,r2-00006799-00006802-00006803,r2-00006800-00006802-00006803,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
pd.merge(spectra_headers, df_concat, on=["PLATEID", "MJD", "FIBERID"], how="left")

,SIMPLE,BITPIX,NAXIS,EXTEND,TAI,RA_x,DEC_x,EQUINOX,RADECSYS,TAIHMS,...,ZTWEAK_ERR,RELEASE,AVG,ENTROPY,MEDIAN,MODE,P16,P2P5,P84,P97P5
0,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,True,8,0,True,4.477028e+09,45.787818,-0.017770,2000.0,FK5,10:36:49.28,...,0.0,b'dr123 ',0.722702,-4.862206,0.691505,0.7,0.341058,0.016004,1.060799,1.399589
4,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1916,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1917,True,8,0,True,4.477028e+09,45.787818,-0.017770,2000.0,FK5,10:36:49.28,...,0.0,b'dr123 ',-1.000000,0.000000,-1.000000,-1.0,-1.000000,-1.000000,-1.000000,-1.000000
1918,True,8,0,True,4.485300e+09,45.785718,-0.019503,2000.0,FK5,04:33:00.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919,True,8,0,True,4.477028e+09,45.787818,-0.017770,2000.0,FK5,10:36:49.28,...,0.0,b'dr123 ',-1.464883,-6.387717,-1.305606,-0.8,-2.656804,-3.863536,-0.451054,0.167387

In [1]:
h5_file.close()

NameError: name 'h5_file' is not defined